### ISSUE TITLE
Unable to do clean install on MySQL/MariaDB install

### ISSUE THREAD

**Issue by olmari** [TampereHacklab/mulysa#152]
When drfx/settings_local.py has MariaDB(MySQL) defined as backend, and MariaDB has proper table and user credentials etc, clean install of Mulysa stops into first ./migrate.py command with following error:

```
Traceback (most recent call last):
  File "/opt/mulysa/.local/share/virtualenvs/mulysa-K2SY2yL-/lib/python3.7/site-packages/django/db/backends/utils.py", line 86, in _execute
    return self.cursor.execute(sql, params)
  File "/opt/mulysa/.local/share/virtualenvs/mulysa-K2SY2yL-/lib/python3.7/site-packages/django/db/backends/mysql/base.py", line 74, in execute
    return self.cursor.execute(query, args)
  File "/opt/mulysa/.local/share/virtualenvs/mulysa-K2SY2yL-/lib/python3.7/site-packages/MySQLdb/cursors.py", line 209, in execute
    res = self._query(query)
  File "/opt/mulysa/.local/share/virtualenvs/mulysa-K2SY2yL-/lib/python3.7/site-packages/MySQLdb/cursors.py", line 315, in _query
    db.query(q)
  File "/opt/mulysa/.local/share/virtualenvs/mulysa-K2SY2yL-/lib/python3.7/site-packages/MySQLdb/connections.py", line 239, in query
    _mysql.connection.query(self, query)
MySQLdb._exceptions.ProgrammingError: (1146, "Table 'mulysa.users_memberservice' doesn't exist")

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "./manage.py", line 15, in <module>
    execute_from_command_line(sys.argv)
  File "/opt/mulysa/.local/share/virtualenvs/mulysa-K2SY2yL-/lib/python3.7/site-packages/django/core/management/__init__.py", line 401, in execute_from_command_line
    utility.execute()
  File "/opt/mulysa/.local/share/virtualenvs/mulysa-K2SY2yL-/lib/python3.7/site-packages/django/core/management/__init__.py", line 395, in execute
    self.fetch_command(subcommand).run_from_argv(self.argv)
  File "/opt/mulysa/.local/share/virtualenvs/mulysa-K2SY2yL-/lib/python3.7/site-packages/django/core/management/base.py", line 328, in run_from_argv
    self.execute(*args, **cmd_options)
  File "/opt/mulysa/.local/share/virtualenvs/mulysa-K2SY2yL-/lib/python3.7/site-packages/django/core/management/base.py", line 366, in execute
    self.check()
  File "/opt/mulysa/.local/share/virtualenvs/mulysa-K2SY2yL-/lib/python3.7/site-packages/django/core/management/base.py", line 395, in check
    include_deployment_checks=include_deployment_checks,
  File "/opt/mulysa/.local/share/virtualenvs/mulysa-K2SY2yL-/lib/python3.7/site-packages/django/core/management/base.py", line 382, in _run_checks
    return checks.run_checks(**kwargs)
  File "/opt/mulysa/.local/share/virtualenvs/mulysa-K2SY2yL-/lib/python3.7/site-packages/django/core/checks/registry.py", line 72, in run_checks
    new_errors = check(app_configs=app_configs)
  File "/opt/mulysa/.local/share/virtualenvs/mulysa-K2SY2yL-/lib/python3.7/site-packages/django/core/checks/urls.py", line 13, in check_url_config
    return check_resolver(resolver)
  File "/opt/mulysa/.local/share/virtualenvs/mulysa-K2SY2yL-/lib/python3.7/site-packages/django/core/checks/urls.py", line 23, in check_resolver
    return check_method()
  File "/opt/mulysa/.local/share/virtualenvs/mulysa-K2SY2yL-/lib/python3.7/site-packages/django/urls/resolvers.py", line 407, in check
    for pattern in self.url_patterns:
  File "/opt/mulysa/.local/share/virtualenvs/mulysa-K2SY2yL-/lib/python3.7/site-packages/django/utils/functional.py", line 48, in __get__
    res = instance.__dict__[self.name] = self.func(instance)
  File "/opt/mulysa/.local/share/virtualenvs/mulysa-K2SY2yL-/lib/python3.7/site-packages/django/urls/resolvers.py", line 588, in url_patterns
    patterns = getattr(self.urlconf_module, "urlpatterns", self.urlconf_module)
  File "/opt/mulysa/.local/share/virtualenvs/mulysa-K2SY2yL-/lib/python3.7/site-packages/django/utils/functional.py", line 48, in __get__
    res = instance.__dict__[self.name] = self.func(instance)
  File "/opt/mulysa/.local/share/virtualenvs/mulysa-K2SY2yL-/lib/python3.7/site-packages/django/urls/resolvers.py", line 581, in urlconf_module
    return import_module(self.urlconf_name)
  File "/opt/mulysa/.local/share/virtualenvs/mulysa-K2SY2yL-/lib/python3.7/importlib/__init__.py", line 127, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "<frozen importlib._bootstrap>", line 1006, in _gcd_import
  File "<frozen importlib._bootstrap>", line 983, in _find_and_load
  File "<frozen importlib._bootstrap>", line 967, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 677, in _load_unlocked
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/mulysa/mulysa/drfx/urls.py", line 13, in <module>
    path("www/", include("www.urls")),
  File "/opt/mulysa/.local/share/virtualenvs/mulysa-K2SY2yL-/lib/python3.7/site-packages/django/urls/conf.py", line 34, in include
    urlconf_module = import_module(urlconf_module)
  File "/opt/mulysa/.local/share/virtualenvs/mulysa-K2SY2yL-/lib/python3.7/importlib/__init__.py", line 127, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "<frozen importlib._bootstrap>", line 1006, in _gcd_import
  File "<frozen importlib._bootstrap>", line 983, in _find_and_load
  File "<frozen importlib._bootstrap>", line 967, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 677, in _load_unlocked
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/mulysa/mulysa/www/urls.py", line 4, in <module>
    from . import views
  File "/opt/mulysa/mulysa/www/views.py", line 17, in <module>
    from www.forms import (
  File "/opt/mulysa/mulysa/www/forms.py", line 44, in <module>
    class RegistrationServicesFrom(forms.Form):
  File "/opt/mulysa/mulysa/www/forms.py", line 69, in RegistrationServicesFrom
    choices=build_service_choices(),
  File "/opt/mulysa/mulysa/www/forms.py", line 51, in build_service_choices
    for service in MemberService.objects.all():
  File "/opt/mulysa/.local/share/virtualenvs/mulysa-K2SY2yL-/lib/python3.7/site-packages/django/db/models/query.py", line 276, in __iter__
    self._fetch_all()
  File "/opt/mulysa/.local/share/virtualenvs/mulysa-K2SY2yL-/lib/python3.7/site-packages/django/db/models/query.py", line 1261, in _fetch_all
    self._result_cache = list(self._iterable_class(self))
  File "/opt/mulysa/.local/share/virtualenvs/mulysa-K2SY2yL-/lib/python3.7/site-packages/django/db/models/query.py", line 57, in __iter__
    results = compiler.execute_sql(chunked_fetch=self.chunked_fetch, chunk_size=self.chunk_size)
  File "/opt/mulysa/.local/share/virtualenvs/mulysa-K2SY2yL-/lib/python3.7/site-packages/django/db/models/sql/compiler.py", line 1151, in execute_sql
    cursor.execute(sql, params)
  File "/opt/mulysa/.local/share/virtualenvs/mulysa-K2SY2yL-/lib/python3.7/site-packages/django/db/backends/utils.py", line 68, in execute
    return self._execute_with_wrappers(sql, params, many=False, executor=self._execute)
  File "/opt/mulysa/.local/share/virtualenvs/mulysa-K2SY2yL-/lib/python3.7/site-packages/django/db/backends/utils.py", line 77, in _execute_with_wrappers
    return executor(sql, params, many, context)
  File "/opt/mulysa/.local/share/virtualenvs/mulysa-K2SY2yL-/lib/python3.7/site-packages/django/db/backends/utils.py", line 86, in _execute
    return self.cursor.execute(sql, params)
  File "/opt/mulysa/.local/share/virtualenvs/mulysa-K2SY2yL-/lib/python3.7/site-packages/django/db/utils.py", line 90, in __exit__
    raise dj_exc_value.with_traceback(traceback) from exc_value
  File "/opt/mulysa/.local/share/virtualenvs/mulysa-K2SY2yL-/lib/python3.7/site-packages/django/db/backends/utils.py", line 86, in _execute
    return self.cursor.execute(sql, params)
  File "/opt/mulysa/.local/share/virtualenvs/mulysa-K2SY2yL-/lib/python3.7/site-packages/django/db/backends/mysql/base.py", line 74, in execute
    return self.cursor.execute(query, args)
  File "/opt/mulysa/.local/share/virtualenvs/mulysa-K2SY2yL-/lib/python3.7/site-packages/MySQLdb/cursors.py", line 209, in execute
    res = self._query(query)
  File "/opt/mulysa/.local/share/virtualenvs/mulysa-K2SY2yL-/lib/python3.7/site-packages/MySQLdb/cursors.py", line 315, in _query
    db.query(q)
  File "/opt/mulysa/.local/share/virtualenvs/mulysa-K2SY2yL-/lib/python3.7/site-packages/MySQLdb/connections.py", line 239, in query
    _mysql.connection.query(self, query)
django.db.utils.ProgrammingError: (1146, "Table 'mulysa.users_memberservice' doesn't exist")
```

**Comment by Noobidoo** [comment]
A workaround for this is to run makemigrations/migrate with --skip-checks if you have a empty DB.
Reference: https://stackoverflow.com/a/59404998

Don't know if there is a better solution for this.

**Comment by olmari** [comment]
I don't know is there good way in current Django-framework to make first time migration to behave cleanly, but if nothing else lets change instructions to tell first time run:
```
./manage.py makemigrations --skip-checks
./manage.py migrate --skip-checks
```

**Comment by tswfi** [comment]
@olmari is this still a problem? now that migrations are always included there should not be any problems with this. Also the CI process builds from scratch all the time successfully...

**Comment by olmari** [comment]
@tswfi Yes, first time install still needs --skip-checks on both migration commands, tested on mulysa rev https://github.com/TampereHacklab/mulysa/commit/eca63b0a2e72cc8ea329e2ab8d52af9e82f03037

**Comment by tswfi** [comment]
no idea why sometimes the croslinking from pr to issue does not work. 

anyway readme has been updated in #244 to include --skip-checks

closing this.
