### ISSUE TITLE
Errors on front page loads.

### ISSUE THREAD

**Issue by olmari** [TampereHacklab/mulysa#310]
With the oauth backend repo and postgres as database backend I get this error on every pageload anywhere:

```
[17/Jan/2021 13:27:58,814] 312f076b95ef4ba29cea70e78a148dae DEBUG Exception while resolving variable 'redirect_to' in template 'www/index.html'.
Traceback (most recent call last):
  File "/opt/mulysa/.local/share/virtualenvs/mulysa-K2SY2yL-/lib/python3.7/site-packages/django/template/base.py", line 829, in _resolve_lookup
    current = current[bit]
  File "/opt/mulysa/.local/share/virtualenvs/mulysa-K2SY2yL-/lib/python3.7/site-packages/django/template/context.py", line 83, in __getitem__
    raise KeyError(key)
KeyError: 'redirect_to'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/opt/mulysa/.local/share/virtualenvs/mulysa-K2SY2yL-/lib/python3.7/site-packages/django/template/base.py", line 835, in _resolve_lookup
    if isinstance(current, BaseContext) and getattr(type(current), bit):
AttributeError: type object 'RequestContext' has no attribute 'redirect_to'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/opt/mulysa/.local/share/virtualenvs/mulysa-K2SY2yL-/lib/python3.7/site-packages/django/template/base.py", line 843, in _resolve_lookup
    current = current[int(bit)]
ValueError: invalid literal for int() with base 10: 'redirect_to'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/opt/mulysa/.local/share/virtualenvs/mulysa-K2SY2yL-/lib/python3.7/site-packages/django/template/base.py", line 850, in _resolve_lookup
    (bit, current))  # missing attribute
django.template.base.VariableDoesNotExist: Failed lookup for key [redirect_to] in [{'True': True, 'False': False, 'None': None}, {'csrf_token': <SimpleLazyObject: 'ixtI0ueANgk1294yA0vcAxxwGka7TmA3dvd1EaWhEdYOvJwMUeYu0hxtsDk6Tlbr'>, 'request': <WSGIRequest: GET '/www/'>, 'user': <SimpleLazyObject: <django.contrib.auth.models.AnonymousUser object at 0x7eff85ca6ac8>>, 'perms': <django.contrib.auth.context_processors.PermWrapper object at 0x7eff85ca69b0>, 'messages': <django.contrib.messages.storage.fallback.FallbackStorage object at 0x7eff85ca66a0>, 'DEFAULT_MESSAGE_LEVELS': {'DEBUG': 10, 'INFO': 20, 'SUCCESS': 25, 'WARNING': 30, 'ERROR': 40}, 'ASSOCIATION_RULES_URL': 'https://vaasa.hacklab.fi/hacklab/vaasa-hacklab-ry/', 'MEMBERS_GUIDE_URL': 'https://vaasa.hacklab.fi/hacklab/vaasa-hacklab-ry/', 'GITHUB_URL': 'https://github.com/vaasahacklab/mulysa', 'SITENAME': 'Mulysa-dev Vaasa Hacklab', 'SITE_URL': 'https://dev.lataamo.vaasa.hacklab.fi', 'PRIVACY_POLICY_URL': 'https://vaasa.hacklab.fi/hacklab/membership/rekisteriseloste/'}, {}, {'view': <django.views.generic.base.TemplateView object at 0x7eff85ca6828>}]
```

Need still to test with empty database and another database provider as other peoples said "couldn't reproduce". Also SSO-login fails after giving credentials to Mulysa in SSO-query, Propably related.

**Comment by olmari** [comment]
Okay digging further, this seems to be few separate issues and none actually OIDC related... `KeyError: 'redirect_to'` is caused by https://github.com/TampereHacklab/mulysa/blob/master/www/templates/www/base.html#L56 for whatever reason. Then there is some index 0 errors on front page where logged in user lands onto.

OIDC not behaving well doesnt't generate actual errors on testing, but seems that it is rather config related.

**Comment by olmari** [comment]
These doesn't happend anymore, I'm quite sure this "redirect_to" was fixed quite long ago with some batches we (you, @tswfi) made ;P
