### ISSUE TITLE
Door API fails if sending email fails

### ISSUE THREAD

**Issue by olmari** [TampereHacklab/mulysa#385]
If door API is called and user has no access, system sends email to user about the situation, but if SMTP fails for some reason the whole door API call fails to internal 500 instead of actually answering properly to the API call.

Mulysa should be resilient about that, SMTP failing there should not make whole API call to fail.

**Comment by olmari** [comment]
Yet to be determined if similar happen in every place where SMTP is used, but at door API call time it is extra bad to fail like this.

**Comment by tswfi** [comment]
@olmari can you provide a trace?

**Comment by olmari** [comment]
On curl side answer is endless HTML.

Mulysa log:

```
[30/Sep/2022 14:05:04,339] 79e8a435875c43698c0e6722da477e24 ERROR Internal Server Error: /api/v1/access/phone/
Traceback (most recent call last):
  File "/opt/mulysa/.local/share/virtualenvs/mulysa-K2SY2yL-/lib/python3.9/site-packages/django/core/handlers/exception.py", line 55, in inner
    response = get_response(request)
  File "/opt/mulysa/.local/share/virtualenvs/mulysa-K2SY2yL-/lib/python3.9/site-packages/django/core/handlers/base.py", line 197, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "/opt/mulysa/.local/share/virtualenvs/mulysa-K2SY2yL-/lib/python3.9/site-packages/django/views/decorators/csrf.py", line 54, in wrapped_view
    return view_func(*args, **kwargs)
  File "/opt/mulysa/.local/share/virtualenvs/mulysa-K2SY2yL-/lib/python3.9/site-packages/rest_framework/viewsets.py", line 125, in view
    return self.dispatch(request, *args, **kwargs)
  File "/opt/mulysa/.local/share/virtualenvs/mulysa-K2SY2yL-/lib/python3.9/site-packages/rest_framework/views.py", line 509, in dispatch
    response = self.handle_exception(exc)
  File "/opt/mulysa/.local/share/virtualenvs/mulysa-K2SY2yL-/lib/python3.9/site-packages/rest_framework_tracking/base_mixins.py", line 48, in handle_exception
    response = super(BaseLoggingMixin, self).handle_exception(exc)
  File "/opt/mulysa/.local/share/virtualenvs/mulysa-K2SY2yL-/lib/python3.9/site-packages/rest_framework/views.py", line 469, in handle_exception
    self.raise_uncaught_exception(exc)
  File "/opt/mulysa/.local/share/virtualenvs/mulysa-K2SY2yL-/lib/python3.9/site-packages/rest_framework/views.py", line 480, in raise_uncaught_exception
    raise exc
  File "/opt/mulysa/.local/share/virtualenvs/mulysa-K2SY2yL-/lib/python3.9/site-packages/rest_framework/views.py", line 506, in dispatch
    response = handler(request, *args, **kwargs)
  File "/opt/mulysa/mulysa/api/views.py", line 92, in phone
    door_access_denied.send(sender=self.__class__, user=user, method="phone")
  File "/opt/mulysa/.local/share/virtualenvs/mulysa-K2SY2yL-/lib/python3.9/site-packages/django/dispatch/dispatcher.py", line 176, in send
    return [
  File "/opt/mulysa/.local/share/virtualenvs/mulysa-K2SY2yL-/lib/python3.9/site-packages/django/dispatch/dispatcher.py", line 177, in <listcomp>
    (receiver, receiver(signal=self, sender=sender, **named))
  File "/opt/mulysa/mulysa/users/signals.py", line 276, in notify_user_door_access_denied
    send_mail(subject, plaintext_content, from_email, to)
  File "/opt/mulysa/.local/share/virtualenvs/mulysa-K2SY2yL-/lib/python3.9/site-packages/django/core/mail/__init__.py", line 87, in send_mail
    return mail.send()
  File "/opt/mulysa/.local/share/virtualenvs/mulysa-K2SY2yL-/lib/python3.9/site-packages/django/core/mail/message.py", line 298, in send
    return self.get_connection(fail_silently).send_messages([self])
  File "/opt/mulysa/mulysa/utils/emailbackend.py", line 24, in send_messages
    return super(LoggingBackend, self).send_messages(email_messages)
  File "/opt/mulysa/.local/share/virtualenvs/mulysa-K2SY2yL-/lib/python3.9/site-packages/django/core/mail/backends/smtp.py", line 124, in send_messages
    new_conn_created = self.open()
  File "/opt/mulysa/.local/share/virtualenvs/mulysa-K2SY2yL-/lib/python3.9/site-packages/django/core/mail/backends/smtp.py", line 80, in open
    self.connection = self.connection_class(
  File "/usr/lib/python3.9/smtplib.py", line 253, in __init__
    (code, msg) = self.connect(host, port)
  File "/usr/lib/python3.9/smtplib.py", line 339, in connect
    self.sock = self._get_socket(host, port, self.timeout)
  File "/usr/lib/python3.9/smtplib.py", line 310, in _get_socket
    return socket.create_connection((host, port), timeout,
  File "/usr/lib/python3.9/socket.py", line 843, in create_connection
    raise err
  File "/usr/lib/python3.9/socket.py", line 831, in create_connection
    sock.connect(sa)
ConnectionRefusedError: [Errno 111] Connection refused
```

**Comment by olmari** [comment]
With Debug = False, the answer side is more simple:

 ```
 curl -X POST   https://dev.lataamo.vaasa.hacklab.fi/api/v1/access/phone/   -H 'Content-Type: application/json'   -d '{
     "deviceid": "1",
     "payload": "+358000"
   }'

<!doctype html>
<html lang="en">
<head>
  <title>Server Error (500)</title>
</head>
<body>
  <h1>Server Error (500)</h1><p></p>
</body>
</html>
```

Trace on server is same.
