### ISSUE TITLE
First time setup according to instructions fails

### ISSUE THREAD

**Issue by vranki** [TampereHacklab/mulysa#7]
Steps until createsuperuser worked, then:

```
(mulysa-99KQzkl4) cosmo@trabant:/2giganen/home/cosmo/src/mulysa$ python manage.py createsuperuser
Email address: xxx@iki.fi
First name: Xxx
Last name: Yyyy
Mobile phone number: 46846864846
Password: 
Password (again): 
This password is too short. It must contain at least 8 characters.
Bypass password validation and create user anyway? [y/N]: y
Traceback (most recent call last):
  File "manage.py", line 15, in <module>
    execute_from_command_line(sys.argv)
  File "/home/cosmo/.local/share/virtualenvs/mulysa-99KQzkl4/lib/python3.7/site-packages/django/core/management/__init__.py", line 381, in execute_from_command_line
    utility.execute()
  File "/home/cosmo/.local/share/virtualenvs/mulysa-99KQzkl4/lib/python3.7/site-packages/django/core/management/__init__.py", line 375, in execute
    self.fetch_command(subcommand).run_from_argv(self.argv)
  File "/home/cosmo/.local/share/virtualenvs/mulysa-99KQzkl4/lib/python3.7/site-packages/django/core/management/base.py", line 323, in run_from_argv
    self.execute(*args, **cmd_options)
  File "/home/cosmo/.local/share/virtualenvs/mulysa-99KQzkl4/lib/python3.7/site-packages/django/contrib/auth/management/commands/createsuperuser.py", line 61, in execute
    return super().execute(*args, **options)
  File "/home/cosmo/.local/share/virtualenvs/mulysa-99KQzkl4/lib/python3.7/site-packages/django/core/management/base.py", line 364, in execute
    output = self.handle(*args, **options)
  File "/home/cosmo/.local/share/virtualenvs/mulysa-99KQzkl4/lib/python3.7/site-packages/django/contrib/auth/management/commands/createsuperuser.py", line 156, in handle
    self.UserModel._default_manager.db_manager(database).create_superuser(**user_data)
  File "/2giganen/home/cosmo/src/mulysa/users/models.py", line 13, in create_superuser
    user.save(using=self.db)
  File "/home/cosmo/.local/share/virtualenvs/mulysa-99KQzkl4/lib/python3.7/site-packages/django/contrib/auth/base_user.py", line 66, in save
    super().save(*args, **kwargs)
  File "/home/cosmo/.local/share/virtualenvs/mulysa-99KQzkl4/lib/python3.7/site-packages/django/db/models/base.py", line 741, in save
    force_update=force_update, update_fields=update_fields)
  File "/home/cosmo/.local/share/virtualenvs/mulysa-99KQzkl4/lib/python3.7/site-packages/django/db/models/base.py", line 766, in save_base
    update_fields=update_fields,
  File "/home/cosmo/.local/share/virtualenvs/mulysa-99KQzkl4/lib/python3.7/site-packages/django/dispatch/dispatcher.py", line 175, in send
    for receiver in self._live_receivers(sender)
  File "/home/cosmo/.local/share/virtualenvs/mulysa-99KQzkl4/lib/python3.7/site-packages/django/dispatch/dispatcher.py", line 175, in <listcomp>
    for receiver in self._live_receivers(sender)
  File "/2giganen/home/cosmo/src/mulysa/users/signals.py", line 31, in send_user_activated
    previous = models.CustomUser.objects.get(id=instance.id)
  File "/home/cosmo/.local/share/virtualenvs/mulysa-99KQzkl4/lib/python3.7/site-packages/django/db/models/manager.py", line 82, in manager_method
    return getattr(self.get_queryset(), name)(*args, **kwargs)
  File "/home/cosmo/.local/share/virtualenvs/mulysa-99KQzkl4/lib/python3.7/site-packages/django/db/models/query.py", line 408, in get
    self.model._meta.object_name
users.models.DoesNotExist: CustomUser matching query does not exist.
```

**Comment by tswfi** [comment]
ah, the signal is broken. the pre_save tries to read the data from the database but it does not exists yet.
