### ISSUE TITLE
Travis coveralls reporting is broken

### ISSUE THREAD

**Issue by tswfi** [TampereHacklab/mulysa#96]
```
$ coveralls
Traceback (most recent call last):
  File "/home/travis/virtualenv/python3.7.1/bin/coveralls", line 10, in <module>
    sys.exit(wear())
  File "/home/travis/virtualenv/python3.7.1/lib/python3.7/site-packages/coveralls/__init__.py", line 78, in wear
    from coveralls.control import coveralls
  File "/home/travis/virtualenv/python3.7.1/lib/python3.7/site-packages/coveralls/control.py", line 2, in <module>
    from coveralls.report import CoverallsReporter
  File "/home/travis/virtualenv/python3.7.1/lib/python3.7/site-packages/coveralls/report.py", line 6, in <module>
    from coverage.report import Reporter
ImportError: cannot import name 'Reporter' from 'coverage.report' (/home/travis/virtualenv/python3.7.1/lib/python3.7/site-packages/coverage/report.py)
```

Seems that others are also seeing this and pinning vocerage to 4.5.4 seems to help for them.

**Comment by tswfi** [comment]
Yay

![image](https://user-images.githubusercontent.com/1352132/101323456-63196280-3871-11eb-9f66-8182fa539268.png)
